language: java

jdk:
  - oraclejdk7

cache:
  directories:
    - '$HOME/.m2/repository'

script: mvn -B verify

after_success:
  - "[[ ${TRAVIS_TAG} != '' ]] && mvn deploy -DskipTests --settings deploy/settings.xml"
